/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polacheplayer;

import Classes.Cancion;
import Classes.Lista_Canciones;
import Classes.MaxHeapTree;
import Classes.MyAudioPlayer;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static polacheplayer.PlayerWindow.jList1;

/**
 *
 * @author MemoL
 */
public class PlayerWindow extends javax.swing.JFrame {

    /**
     * Creates new form Player
     */
    public PlayerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_6_3931974384.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 350, 80, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_12_8960249327.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 350, 80, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_14_8923130452.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 350, 80, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_16_7723127376.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 350, 100, 70);

        jList1.setBackground(new java.awt.Color(96, 151, 151));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 580, 280);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_18_8245545525.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(620, 120, 80, 70);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_1_8797561459.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(620, 220, 80, 70);

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 11)); // NOI18N
        jLabel1.setText("Add Song/Album");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 100, 100, 13);

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 11)); // NOI18N
        jLabel3.setText("Shuffle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 200, 50, 13);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/witcher-3-geralt-11.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1140, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (theplayer != null) {
            theplayer.close();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione una cancion o album");
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MPEG3 songs", "mp3");
        chooser.addChoosableFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        File dir = null;

        String extension = "mp3";
        //File[] files = null;
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile().isDirectory()) {
                dir = chooser.getCurrentDirectory();
                //files = dir.listFiles();
                //System.out.println(files.length);
                // cogiendo todos los archivos mp3
                for (int i = 0; i < dir.listFiles().length; i++) {
                    if (dir.listFiles()[i].getName().endsWith(".mp3")) {
                        todas.insert((new Cancion(dir.listFiles()[i].getName())), cont);
                        System.out.println(dir.getAbsolutePath() + "\\" + dir.listFiles()[i].getName());
                        todas.get(cont).setURL(dir.getAbsolutePath() + "\\" + dir.listFiles()[i].getName());
                        cont++;
                        todas.setSize(cont);
                    }
                }
                
                // insertando al modelo de la jlist
                for (int i = 0; i < cont; i++) {
                    model.addElement(todas.get(i).getName());
                }
            } else {
                
                todas.insert(new Cancion(chooser.getSelectedFile().getName()), cont);
                System.out.println(chooser.getSelectedFile().getAbsolutePath());
                todas.get(cont).setURL(chooser.getSelectedFile().getAbsolutePath());
                cont++;
                todas.setSize(cont);
                model.addElement(chooser.getSelectedFile().getName());
            }
            jList1.setModel(model);
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
//        try{
//            System.out.println(todas.get(jList1.getSelectedIndex()).getURL());
//            FileInputStream fis = new FileInputStream(todas.get(jList1.getSelectedIndex()).getURL());
//            Player play =  new Player(fis);
//            play.play();
//        }catch(Exception e){
//            System.out.println(e);
//        }
        if (theplayer != null) {
            theplayer.close();
        }
        System.out.println(todas.get(jList1.getSelectedIndex()).getURL());
        theplayer = new MyAudioPlayer(todas.get(jList1.getSelectedIndex()).getURL(), false);
        todas.get(jList1.getSelectedIndex()).setPriority();
        theplayer.start();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if (cont == jList1.getSelectedIndex() + 1) {
            JOptionPane.showMessageDialog(this, "No hay mas canciones");
        } else {

            if (theplayer != null) {
                theplayer.close();
            }
            theplayer = new MyAudioPlayer(todas.get(jList1.getSelectedIndex() + 1).getURL(), false);
            todas.get(jList1.getSelectedIndex()).setPriority();
            theplayer.start();
            jList1.setSelectedIndex(jList1.getSelectedIndex() + 1);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (-1 == jList1.getSelectedIndex() - 1) {
            JOptionPane.showMessageDialog(this, "No hay mas canciones");
        } else {

            if (theplayer != null) {
                theplayer.close();
            }
            theplayer = new MyAudioPlayer(todas.get(jList1.getSelectedIndex() - 1).getURL(), false);
            todas.get(jList1.getSelectedIndex()).setPriority();
            theplayer.start();
            jList1.setSelectedIndex(jList1.getSelectedIndex() - 1);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        tree = new MaxHeapTree(todas.get(0));
        for (int i = 0; i < cont; i++) {
            System.out.println("pruebita: "+ todas.get(i).getPriority());
            tree.insert(todas.get(i));
        }
        System.out.println("el remove"+ tree.remove().getName());
       
//        while(tree.remove()!=null){
//            model1.addElement(tree.remove().getName());
//        }
//        jList1.setModel(model1);
//        for (int i = 0; i < todas.getSize(); i++) {
//            model1.addElement(tree.remove());
//        }
//        jList1.setModel(model1);
        //ahora a setear al nuevo model
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayerWindow player = new PlayerWindow();
                player.setSize(1080, 580);
                player.setResizable(false);
                player.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
DefaultListModel model = new DefaultListModel();
    DefaultListModel model1 = new DefaultListModel();
    Lista_Canciones todas = new Lista_Canciones();
    MyAudioPlayer theplayer;
    public static int cont = 0;
    MaxHeapTree tree;
}
